server:
  port: 8091
spring:
  application:
    name: hotel-service
  data:
    mongodb:
      database: hotelService
      uri: mongodb://localhost:27017
  error:
    include-message: always


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka




