server:
  port: 8093
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rakesh8874/microservice_configuration
          clone-on-start: true